name: Hardware Targets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabi, riscv32imac-unknown-none-elf

      - name: Verify ARM Target Compilation
        run: cargo check --target thumbv7em-none-eabi --release -p core_sec_verifier --lib

      - name: Verify RISC-V Target Compilation
        run: cargo check --target riscv32imac-unknown-none-elf --release -p core_sec_verifier --lib
